// =============================================================================
// CICS Emulation - Document Handler Example
// =============================================================================

#include <cics/document/document.hpp>
#include <iostream>

using namespace cics;
using namespace cics::document;

int main() {
    std::cout << "\n";
    std::cout << "+==============================================================+\n";
    std::cout << "|      CICS Emulation - Document Handler Example    |\n";
    std::cout << "|                        Version 3.4.6                         |\n";
    std::cout << "+==============================================================+\n\n";
    
    DocumentManager::instance().initialize();
    
    // 1. Create a document
    std::cout << "1. Creating Document\n";
    std::cout << "---------------------------------------------------------------\n";
    
    auto token_result = exec_cics_document_create(DocumentType::HTML);
    if (token_result.is_error()) {
        std::cerr << "Failed to create document\n";
        return 1;
    }
    String token = token_result.value();
    std::cout << "   Document created with token: " << token << "\n\n";
    
    // 2. Set content with symbols
    std::cout << "2. Setting Content with Symbols\n";
    std::cout << "---------------------------------------------------------------\n";
    
    String html_template = R"(
<!DOCTYPE html>
<html>
<head><title>&TITLE;</title></head>
<body>
    <h1>Welcome, &USERNAME;!</h1>
    <p>Account: &ACCOUNT;</p>
    <p>Balance: $&BALANCE;</p>
</body>
</html>
)";
    
    exec_cics_document_set(token, html_template);
    std::cout << "   Template set with 4 symbol placeholders\n";
    
    // 3. Set symbol values
    std::cout << "\n3. Setting Symbol Values\n";
    std::cout << "---------------------------------------------------------------\n";
    
    exec_cics_document_set_symbol(token, "TITLE", "Account Summary");
    exec_cics_document_set_symbol(token, "USERNAME", "John Smith");
    exec_cics_document_set_symbol(token, "ACCOUNT", "1234-5678-9012");
    exec_cics_document_set_symbol(token, "BALANCE", "15,432.50");
    
    std::cout << "   TITLE    = Account Summary\n";
    std::cout << "   USERNAME = John Smith\n";
    std::cout << "   ACCOUNT  = 1234-5678-9012\n";
    std::cout << "   BALANCE  = 15,432.50\n\n";
    
    // 4. Retrieve with symbol substitution
    std::cout << "4. Retrieving Document (with symbol substitution)\n";
    std::cout << "---------------------------------------------------------------\n";
    
    auto content = exec_cics_document_retrieve(token);
    if (content.is_success()) {
        std::cout << content.value() << "\n";
    }
    
    // 5. Insert additional content
    std::cout << "5. Inserting Additional Content\n";
    std::cout << "---------------------------------------------------------------\n";
    
    exec_cics_document_insert(token, "<!-- Generated by CICS Emulation -->\n", InsertPosition::ATSTART);
    std::cout << "   Inserted comment at start of document\n\n";
    
    // 6. Document statistics
    std::cout << "6. Document Statistics\n";
    std::cout << "---------------------------------------------------------------\n";
    
    auto stats = DocumentManager::instance().get_stats();
    std::cout << "   Documents created:  " << stats.documents_created << "\n";
    std::cout << "   Inserts executed:   " << stats.inserts_executed << "\n";
    std::cout << "   Retrieves executed: " << stats.retrieves_executed << "\n";
    std::cout << "   Bytes written:      " << stats.bytes_written << "\n";
    std::cout << "   Symbols substituted: " << stats.symbols_substituted << "\n\n";
    
    // Cleanup
    exec_cics_document_delete(token);
    DocumentManager::instance().shutdown();
    
    std::cout << "================================================================\n";
    std::cout << "   Document Handler example completed successfully!\n";
    std::cout << "================================================================\n\n";
    
    return 0;
}
